config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :thing_with_react_forms
  resources :thing_with_rails_forms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing_with_rails_form.rb
class ThingWithRailsForm < ApplicationRecord
  has_one_attached :image
end

app/models/thing_with_react_form.rb
class ThingWithReactForm < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/thing_with_rails_forms_controller.rb
class ThingWithRailsFormsController < ApplicationController
  before_action :set_thing_with_rails_form, only: [:show, :edit, :update, :destroy]

  # GET /thing_with_rails_forms
  # GET /thing_with_rails_forms.json
  def index
    @thing_with_rails_forms = ThingWithRailsForm.all
  end

  # GET /thing_with_rails_forms/1
  # GET /thing_with_rails_forms/1.json
  def show
  end

  # GET /thing_with_rails_forms/new
  def new
    @thing_with_rails_form = ThingWithRailsForm.new
  end

  # GET /thing_with_rails_forms/1/edit
  def edit
  end

  # POST /thing_with_rails_forms
  # POST /thing_with_rails_forms.json
  def create
    @thing_with_rails_form = ThingWithRailsForm.new(thing_with_rails_form_params)

    respond_to do |format|
      if @thing_with_rails_form.save
        format.html { redirect_to @thing_with_rails_form, notice: 'Thing with rails form was successfully created.' }
        format.json { render :show, status: :created, location: @thing_with_rails_form }
      else
        format.html { render :new }
        format.json { render json: @thing_with_rails_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thing_with_rails_forms/1
  # PATCH/PUT /thing_with_rails_forms/1.json
  def update
    respond_to do |format|
      if @thing_with_rails_form.update(thing_with_rails_form_params)
        format.html { redirect_to @thing_with_rails_form, notice: 'Thing with rails form was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing_with_rails_form }
      else
        format.html { render :edit }
        format.json { render json: @thing_with_rails_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thing_with_rails_forms/1
  # DELETE /thing_with_rails_forms/1.json
  def destroy
    @thing_with_rails_form.destroy
    respond_to do |format|
      format.html { redirect_to thing_with_rails_forms_url, notice: 'Thing with rails form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing_with_rails_form
      @thing_with_rails_form = ThingWithRailsForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_with_rails_form_params
      params.require(:thing_with_rails_form).permit(:name, :image)
    end
end

app/controllers/thing_with_react_forms_controller.rb
class ThingWithReactFormsController < ApplicationController
  before_action :set_thing_with_react_form, only: [:show, :edit, :update, :destroy]

  # GET /thing_with_react_forms
  # GET /thing_with_react_forms.json
  def index
    @thing_with_react_forms = ThingWithReactForm.all
  end

  # GET /thing_with_react_forms/1
  # GET /thing_with_react_forms/1.json
  def show
  end

  # GET /thing_with_react_forms/new
  def new
    @thing_with_react_form = ThingWithReactForm.new
  end

  # GET /thing_with_react_forms/1/edit
  def edit
  end

  # POST /thing_with_react_forms
  # POST /thing_with_react_forms.json
  def create
    @thing_with_react_form = ThingWithReactForm.new(thing_with_react_form_params)

    respond_to do |format|
      if @thing_with_react_form.save
        format.html { redirect_to @thing_with_react_form, notice: 'Thing with react form was successfully created.' }
        format.json { render :show, status: :created, location: @thing_with_react_form }
      else
        format.html { render :new }
        format.json { render json: @thing_with_react_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thing_with_react_forms/1
  # PATCH/PUT /thing_with_react_forms/1.json
  def update
    respond_to do |format|
      if @thing_with_react_form.update(thing_with_react_form_params)
        format.html { redirect_to @thing_with_react_form, notice: 'Thing with react form was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing_with_react_form }
      else
        format.html { render :edit }
        format.json { render json: @thing_with_react_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thing_with_react_forms/1
  # DELETE /thing_with_react_forms/1.json
  def destroy
    @thing_with_react_form.destroy
    respond_to do |format|
      format.html { redirect_to thing_with_react_forms_url, notice: 'Thing with react form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing_with_react_form
      @thing_with_react_form = ThingWithReactForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_with_react_form_params
      params.require(:thing_with_react_form).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thing_with_rails_forms_helper.rb
module ThingWithRailsFormsHelper
end

app/helpers/thing_with_react_forms_helper.rb
module ThingWithReactFormsHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStorageDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'thing-with-react-form-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/thing_with_rails_forms/_form.html.erb
<%= form_with(model: thing_with_rails_form, local: true) do |form| %>
  <% if thing_with_rails_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thing_with_rails_form.errors.count, "error") %> prohibited this thing_with_rails_form from being saved:</h2>

      <ul>
      <% thing_with_rails_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thing_with_rails_forms/edit.html.erb
<h1>Editing Thing With Rails Form</h1>

<%= render 'form', thing_with_rails_form: @thing_with_rails_form %>

<%= link_to 'Show', @thing_with_rails_form %> |
<%= link_to 'Back', thing_with_rails_forms_path %>

app/views/thing_with_rails_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thing With Rails Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thing_with_rails_forms.each do |thing_with_rails_form| %>
      <tr>
        <td><%= thing_with_rails_form.name %></td>
        <td><%= link_to 'Show', thing_with_rails_form %></td>
        <td><%= link_to 'Edit', edit_thing_with_rails_form_path(thing_with_rails_form) %></td>
        <td><%= link_to 'Destroy', thing_with_rails_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing With Rails Form', new_thing_with_rails_form_path %>

app/views/thing_with_rails_forms/new.html.erb
<h1>New Thing With Rails Form</h1>

<%= render 'form', thing_with_rails_form: @thing_with_rails_form %>

<%= link_to 'Back', thing_with_rails_forms_path %>

app/views/thing_with_rails_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing_with_rails_form.name %>
</p>

<% if @thing_with_rails_form.image.attached? %>
  <p>
    <strong>Image:</strong>
    <br>
    <%= image_tag @thing_with_rails_form.image %>
  </p>
<% end %>

<%= link_to 'Edit', edit_thing_with_rails_form_path(@thing_with_rails_form) %> |
<%= link_to 'Back', thing_with_rails_forms_path %>

app/views/thing_with_react_forms/_form.html.erb
<%= form_with(model: thing_with_react_form, local: true) do |form| %>
  <% if thing_with_react_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thing_with_react_form.errors.count, "error") %> prohibited this thing_with_react_form from being saved:</h2>

      <ul>
      <% thing_with_react_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thing_with_react_forms/edit.html.erb
<h1>Editing Thing With React Form</h1>

<%= render 'form', thing_with_react_form: @thing_with_react_form %>

<%= link_to 'Show', @thing_with_react_form %> |
<%= link_to 'Back', thing_with_react_forms_path %>

app/views/thing_with_react_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thing With React Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thing_with_react_forms.each do |thing_with_react_form| %>
      <tr>
        <td><%= thing_with_react_form.name %></td>
        <td><%= link_to 'Show', thing_with_react_form %></td>
        <td><%= link_to 'Edit', edit_thing_with_react_form_path(thing_with_react_form) %></td>
        <td><%= link_to 'Destroy', thing_with_react_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing With React Form', new_thing_with_react_form_path %>

app/views/thing_with_react_forms/new.html.erb
<h1>New Thing With React Form</h1>

<%= react_component 'FormForThingWithReactForm' %>

<%= link_to 'Back', thing_with_react_forms_path %>

app/views/thing_with_react_forms/show.html.erb
<p id="notice"><%= notice %></p>

<%= react_component 'ShowThingWithReactForm',
    props: @thing_with_react_form.attributes
              .merge(
                image: url_for(@thing_with_react_form.image)
              )
%>

<%= link_to 'Edit', edit_thing_with_react_form_path(@thing_with_react_form) %> |
<%= link_to 'Back', thing_with_react_forms_path %>